---
apiVersion: v1
kind: Service
metadata:
  name: textgen-gpt2
  labels:
    app: textgen-gpt2
spec:
  type: ClusterIP 
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: textgen-gpt2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: textgen-gpt2 
  labels:
    app: textgen-gpt2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: textgen-gpt2
  template:
    metadata:
      labels:
        app: textgen-gpt2
    spec:
      containers:
      - name: textgen-gpt2
        # runtimeClassName: kontain
        image: 782340374253.dkr.ecr.us-east-1.amazonaws.com/textgen-gpt2:latest
        imagePullPolicy: IfNotPresent # or Never
        ports:
        - containerPort: 5000
