apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: textgen-gpt2-ksvc
spec:
  template:
    spec:
      # runtimeClassName: kontain
      imagePullSecrets:
      - name: container-registry # secret name
      containers:
        - image: 782340374253.dkr.ecr.us-east-1.amazonaws.com/textgen-gpt2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000